import { Dimensions, StyleSheet } from "react-native";

const PaymentHistoryStyle = StyleSheet.create({
    container:{
        flex:1,
        backgroundColor:'#efedf3',
        flexDirection:'column'
    },
    bankLoanView:{
        height:Dimensions.get('screen').height*0.25,
        width:'100%',
        backgroundColor:'#ffffff',
        alignItems:'center',
        borderRadius:20,
        elevation:1
    },
    loanDetailView:{
        width:'90%',
        backgroundColor:'#f8f6ff',
        marginTop:15,
        borderRadius:10,
        padding:10,
        display:'flex',
        flexDirection:'row'
    },
    bankIcon:{
        borderWidth:1,
        borderRadius:30,
        padding:10,
        opacity:0.7
    },
    bankNameView:{
        marginLeft:10,
        justifyContent:'center'
    },
    bankNameText:{
        fontSize:16,
        fontWeight:'400'
    },
    bankNameSubText:{
        color:'grey',
        fontSize:12,
        marginTop:2
    },
    activeDateView:{
        position:'absolute',
        right:10,
        alignSelf:'center', 
    },
    activeText:{
        color:'#23ac53',
        fontSize:13,
        fontWeight:'500',
        textAlign:'right'
    },
    dateIssueText:{
        marginTop:5,
        fontSize:12
    },
    sliderTopView:{
        width:'85%',
        display:'flex',
        flexDirection:'row'
    },
    sliderText:{
        color:'grey'
    },
    sliderBottomView:{
        width:'85%',
        display:'flex',
        flexDirection:'row'
    },
    paymentHistoryText:{
        fontSize:16,
        fontWeight:'600'
    },
    footer:{
        position:'absolute',
        bottom:0,
        backgroundColor:'white',
        width:'100%',
        height:Dimensions.get('screen').height*0.11,
        borderRadius:20,
        alignItems:'center',
        justifyContent:'center'
    },
    button:{
        width:'90%',
        height:50,
        backgroundColor:'#3f1369',
        alignItems:'center',
        justifyContent:'center',
        borderRadius:20
    },
    buttonText:{
        color:'#ffffff',
        fontSize:16,
        fontWeight:'600'
    }
})
export default PaymentHistoryStyle;